---
- name: "Install Chrony using package module"
  become: yes
  package:
    name: chrony
    state: present
  tags:
    - chrony-install
    - chrony
  ignore_errors: yes

- name: "Fallback: Install Chrony using raw command on Amazon Linux 2023"
  become: yes
  raw: |
    yum install -y chrony
  when: ansible_os_family == 'RedHat' and
        ansible_distribution == 'Amazon' and
        ansible_distribution_major_version != '2'
  tags:
    - chrony-install
    - chrony