---
- name: 'include os-specific vars'
  include_vars: "{{ansible_os_family | lower }}.yml"
  tags:
    - 'chrony'
    - 'chrony-vars'

- import_tasks: "install.yml"
  when: not (air_gap | default(false))
- import_tasks: "configure.yml"
- import_tasks: "service.yml"
